### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by yassineyahyaoui** [yassinelogtari/testimonial#1]
img "right-quote.png" has a class called class="quote" not class="quaote"

**Comment by Shubham56-droid** [comment]
i will correct  it

**Comment by yassineyahyaoui** [comment]
i have if you want to take a look

**Comment by Shubham56-droid** [comment]
Pls follow me if you like my work I promise to contribute more😀

**Comment by yassinelogtari** [comment]
thanks for the advice!
